apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
  annotations:
    backstage.io/spectral-ruleset-url: https://github.com/DawMatt/backstage/blob/main/data/spectral-openapi.yaml
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
